### ISSUE TITLE
Subfolder end slash

### ISSUE THREAD

**Issue by Treniota** [chsmedien/XRouting#19]
Plugin only works when web address is written with slash at the end "www.domain.com/lang/"
"www.domain.com/lang" results in Page Not Found. The problem is that many people wouldn't care to type slash at the end - they would just hit enter after "lang". Is there any way to redirect www.domain.com/lang to www.domain.com/lang/? Thank You!

**Comment by christianseel** [comment]
Hi @Treniota, XRouting definitely works also without the trailing slash! Any chance you have some RewriteRules in your htaccess for example that are causing the issue? XRouting does not require any changes to the default MODX htaccess…

Also make sure that the resource with the alias "lang" is not a container in that case, because then MODX would require the slash.

**Comment by Treniota** [comment]
I set XRouting up as written in manual here: https://modx.today/posts/2015/05/using-xrouting-for-multilingual-websites-in-modx. 
I didn't created any real "lang" ("ru" in real world) subfolder in server.  .htaccess is entirely standard. Though there is no real resource or subfolder on server with "ru" alias. "ru" is a virtual subfolder for new context. Here is how it functions in my case:
http://www.baldai-druskininkai.lt/
http://www.baldai-druskininkai.lt/ru/
http://www.baldai-druskininkai.lt/ru
http://www.baldai-druskininkai.lt/ru/russian.html
http://www.baldai-druskininkai.lt/ru/russian/rus.html

Everything is ok except http://www.baldai-druskininkai.lt/ru which redirects to error_page of standard web context. Every resource is not a container.

**Comment by christianseel** [comment]
Ah now I understand it… Mh yeah, this is "by design" and how XRouting works… XRouting matches based on the `base_url` context setting which would be `/ru/` in your case… So `domain.com/ru` wouldn't match that.

I could image that this is something XRouting could handle better but that would require some tests to prevent other issues.

In the meantime you could add something like the following RewriteRule to your htaccess:
`RewriteRule ^([^/]+)$ $1/ [R=301,L]`
…that should append a slash to all "language folders".

**Comment by Treniota** [comment]
After going through trial and error I've found that I need to put to .htaccess this (before FURL rewrite rule):

RewriteCond %{REQUEST_URI} ^/(ru)$
RewriteRule ^(.*)$ http://%{HTTP_HOST}/$1/ [R=301,L]

Then everything works as expected.

RewriteRule ^([^/]+)$ $1/ [R=301,L] 
gives this:
http://www.domain.com/index.php/?q=ru/

And also I have found, that if I use default "web" context for primary language I need to add in its context settings http_host (domain.com), base_url (/) and site_url (http://www.domain.com/), otherwise it returns page not found error.

Thank you for plugin, even if it is not the perfect, but it was the only one that did what I wanted it to do at the end.
